[package]
name = "rust-the-book"
version = "0.1.0"
authors = ["Fabio Scotto di Santolo <fabio.scottodisantolo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
